# Generated by Django 5.1.6 on 2025-03-08 18:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('user', 'User'), ('transaction', 'Transaction')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
